[mypy]
ignore_missing_imports = True
explicit_package_bases = True
namespace_packages = True
disable_error_code = var-annotated, import, call-arg, arg-type, union-attr, attr-defined, assignment, misc, call-overload

[mypy-utils.scoring.llm_judge.tests.*]
ignore_errors = True

