#!/bin/bash
MODELS=(
  "claude-haiku-4-5-20251001"
  "claude-opus-4-5-20251101"
  "claude-opus-4-6"
  "claude-opus-4-7"
  "claude-sonnet-4-5-20250929"
  "claude-sonnet-4-6"
  "codestral-latest"
  "CognitiveComputations_dolphin-mistral-nemo_latest"
  "deepseek_deepseek-v4-flash"
  "deepseek_deepseek-v4-pro"
  "deepseek-r1_8b"
  "deepseek-v3.1_671b-cloud"
  "deepseek-v3.2_cloud"
  "gemini-2.5-flash"
  "gemini-2.5-pro"
  "gemini-3-flash-preview"
  "gemini-3.1-pro-preview"
  "gemma3_12b"
  "gemma3_4b"
  "gemma4_26b"
  "gemma4_31b-cloud"
  "gemma4_E4B"
  "gemma4_e2b"
  "glm-5_cloud"
  "glm-5.1_cloud"
  "gpt-4o"
  "gpt-4o-mini"
  "gpt-5"
  "gpt-5-mini"
  "gpt-5.4"
  "gpt-5.4-mini"
  "gpt-oss_120b-cloud"
  "gpt-oss_20b-cloud"
  "grok-3-mini"
  "grok-4-1-fast-reasoning"
  "grok-4-fast-non-reasoning"
  "grok-4.20-0309-non-reasoning"
  "grok-4.20-0309-reasoning"
  "grok-4.3"
  "hermes3_8b"
  "hf.co_bartowski_NousResearch_Hermes-4-14B-GGUF_Q4_K_M"
  "hf.co_mradermacher_Ministral-3-14B-abliterated-GGUF_Q8_0"
  "kimi-k2.5_cloud"
  "llama-3.3-70b-versatile"
  "magistral-medium-latest"
  "magistral-small-latest"
  "meta-llama_llama-4-scout-17b-16e-instruct"
  "minimax_minimax-m2.7"
  "minimax_minimax-m2.7-20260318"
  "minimax-m2.7_cloud"
  "ministral-3_14b"
  "ministral-3_8b"
  "mistral-large-3"
  "mistral-medium-2312"
  "mistral-medium-3-5"
  "mistral-small-2603"
  "mistral-small-3"
  "moonshotai_kimi-k2"
  "moonshotai_kimi-k2-thinking-20251106"
  "moonshotai_kimi-k2.5"
  "moonshotai_kimi-k2.6"
  "nousresearch_hermes-4-405b"
  "nousresearch_hermes-4-70b"
  "o1"
  "o3-mini"
  "o4-mini"
  "qwen_qwen3-32b"
  "qwen2.5_3b"
  "qwen2.5-coder_7b"
  "qwen2.5vl_7b"
  "qwen3_14b"
  "qwen3_4b"
  "qwen3.5_397b-cloud"
  "qwen3.5_9b"
  "z-ai_glm-4.6"
  "z-ai_glm-4.7"
  "z-ai_glm-5"
  "z-ai_glm-5-turbo"
  "z-ai_glm-5.1"
)

LOGFILE="review_batch.log"
TOTAL=${#MODELS[@]}
echo "Start: $(date)" > "$LOGFILE"
echo "Modelle gesamt: $TOTAL" >> "$LOGFILE"

for i in "${!MODELS[@]}"; do
  model="${MODELS[$i]}"
  num=$((i + 1))
  echo "[$num/$TOTAL] $model -- $(date +%H:%M:%S)" | tee -a "$LOGFILE"
  if .venv/bin/python scripts/analysis/generate_review.py --model "$model" --auto --force >> "$LOGFILE" 2>&1; then
    echo "  OK" | tee -a "$LOGFILE"
  else
    echo "  FEHLER" | tee -a "$LOGFILE"
  fi
done

echo "Fertig: $(date)" | tee -a "$LOGFILE"
