"""Re-Export-Bridge für utils.model_utils — Aufspaltung in Submodule (Sektion A).

Alle Funktionen wurden in logische Submodule verschoben. Dieses Modul
re-exportiert die öffentliche API für Abwärtskompatibilität.
Submodule: model_id_base, model_card_io, model_version, model_size_class,
model_thinking, model_id, model_token_budget.
"""
__all__ = [
    "T",
    "_PROVIDER_SHORTCODES",
    "_LOCAL_PROVIDER_NAMES",
    "_PROVIDER_ALIAS_MAP",
    "_QUANT_FORMAT_TOKENS",
    "_HF_OLLAMA_RE",
    "_VERSION_UNDERSCORE_RE",
    "get_provider_shortcode",
    "get_hardware_profile",
    "model_version_has_quant_pollution",
    "normalize_model_id",
    "_safe_name",
    "safe_name_for_filesystem",
    "safe_slugify",
    "normalize_for_comparison",
    "internal_id_to_config_form",
    "find_model_in_provider_cfg",
    "resolve_model_cfg_for",
    "strip_date_suffix",
    "get_commercial_models_from_config",
    "is_cloud_model",
    "resolve_provider",
    "CARD_DIR",
    "_STALE_VERSIONS",
    "_id_logger",
    "_card_path",
    "build_card_id",
    "resolve_unique_card_id",
    "_find_card",
    "find_card_by_heritage_id",
    "SUPPORT_TOOL_USE_UNTESTED",
    "SUPPORT_TOOL_USE_NOT_APPLICABLE",
    "_SUPPORT_TOOL_USE_VALUES",
    "normalize_supports_tool_use",
    "update_model_card_tooluse_fields",
    "_extract_ollama_id",
    "_get_local_model_hash_version",
    "get_model_version",
    "format_version_hash_for_display",
    "get_ollama_model_info",
    "is_model_suitable_for_benchmark",
    "get_ollama_models_info",
    "_load_size_class_taxonomy",
    "_SIZE_CLASS_VALID",
    "_SIZE_CLASS_THRESHOLDS",
    "_SIZE_CLASS_TAXONOMY_PATH",
    "_param_b_to_size_class",
    "get_model_size_class",
    "_THINK_TAGS",
    "_PROBE_PROMPTS",
    "_PROBE_PROMPT",
    "_PROBE_MAX_TOKENS",
    "_PROBE_BUDGET_EXHAUSTION_RATIO",
    "_INLINE_COT_LENGTH_THRESHOLD",
    "_INLINE_COT_OPS",
    "_INLINE_COT_MIN_OPS",
    "_COT_FAMILY_MAP",
    "_has_inline_cot",
    "_find_think_tags",
    "classify_cot_marker_family",
    "ThinkingProbeResult",
    "_probe_single",
    "probe_thinking_model",
    "_is_override_active",
    "resolve_effective_thinking",
    "is_reasoning_model_from_card",
    "is_reasoning_model",
    "is_thinking_optional_from_card",
    "_read_max_output_tokens_from_card",
    "WEIGHTS_TIER_DISPLAY",
    "resolve_canonical_model_id",
    "enforce_card_first",
    "get_model_category",
    "get_use_case_primary",
    "get_model_identity",
    "get_model_specialization",
    "resolve_token_budget",
    "logger",
]

# Re-Export aller öffentlichen und privaten Namen, die von externen
# Modulen importiert werden (verifiziert via rg "from utils.model_utils import").
from utils.model_id_base import (
    T,
    _PROVIDER_SHORTCODES,
    _LOCAL_PROVIDER_NAMES,
    _PROVIDER_ALIAS_MAP,
    _QUANT_FORMAT_TOKENS,
    _HF_OLLAMA_RE,
    _VERSION_UNDERSCORE_RE,
    get_provider_shortcode,
    get_hardware_profile,
    model_version_has_quant_pollution,
    normalize_model_id,
    _safe_name,
    safe_name_for_filesystem,
    safe_slugify,
    normalize_for_comparison,
    internal_id_to_config_form,
    find_model_in_provider_cfg,
    resolve_model_cfg_for,
    strip_date_suffix,
    get_commercial_models_from_config,
    is_cloud_model,
    resolve_provider,
)
from utils.model_card_io import (
    CARD_DIR,
    _STALE_VERSIONS,
    _id_logger,
    _card_path,
    build_card_id,
    resolve_unique_card_id,
    _find_card,
    find_card_by_heritage_id,
    SUPPORT_TOOL_USE_UNTESTED,
    SUPPORT_TOOL_USE_NOT_APPLICABLE,
    _SUPPORT_TOOL_USE_VALUES,
    normalize_supports_tool_use,
    update_model_card_tooluse_fields,
)
from utils.model_version import (
    _extract_ollama_id,
    _get_local_model_hash_version,
    get_model_version,
    format_version_hash_for_display,
    get_ollama_model_info,
    is_model_suitable_for_benchmark,
    get_ollama_models_info,
)
from utils.model_size_class import (
    _load_size_class_taxonomy,
    _SIZE_CLASS_VALID,
    _SIZE_CLASS_THRESHOLDS,
    _SIZE_CLASS_TAXONOMY_PATH,
    _param_b_to_size_class,
    get_model_size_class,
)
from utils.model_thinking import (
    _THINK_TAGS,
    _PROBE_PROMPTS,
    _PROBE_PROMPT,
    _PROBE_MAX_TOKENS,
    _PROBE_BUDGET_EXHAUSTION_RATIO,
    _INLINE_COT_LENGTH_THRESHOLD,
    _INLINE_COT_OPS,
    _INLINE_COT_MIN_OPS,
    _COT_FAMILY_MAP,
    _has_inline_cot,
    _find_think_tags,
    classify_cot_marker_family,
    ThinkingProbeResult,
    _probe_single,
    probe_thinking_model,
    _is_override_active,
    resolve_effective_thinking,
    is_reasoning_model_from_card,
    is_reasoning_model,
    is_thinking_optional_from_card,
    _read_max_output_tokens_from_card,
)
from utils.model_id import (
    WEIGHTS_TIER_DISPLAY,
    resolve_canonical_model_id,
    enforce_card_first,
    get_model_category,
    get_use_case_primary,
    get_model_identity,
    get_model_specialization,
)
from utils.model_token_budget import resolve_token_budget

# logger für Abwärtskompatibilität (viele Module tun `from utils.model_utils import logger`)
import logging
logger = logging.getLogger(__name__)
